### ISSUE TITLE
vim-slime with neovim, tmux causes "divide by zero" issue in wezterm after `plt.show()` was send

### ISSUE THREAD

**Issue by ucl98** [jpalardy/vim-slime#448]
I am using Neovim, WezTerm, and Tmux. My setup involves sending lines from Neovim to a Tmux window where an IPython session is running. This setup works well and allows for plot display in WezTerm without issues.

However, I encounter a problem when sending the command `plt.show()` via vim-slime; it causes WezTerm to panic. In contrast, when I manually type `plt.show()` in the same IPython instance, the plot displays correctly with no issues. Notably, lines 18-21 are sent via vim-slime, and lines 22-25 are typed manually.

## Versions

- **Neovim:**
  - NVIM v0.10.2
  - Build type: Release
  - LuaJIT 2.1.1713484068

- **vim-slime**
 - vim-slime (version from 27.11.24)

- **matplotlib-backend-wezterm**
  - matplotlib-backend-wezterm 2.1.2 

- **WezTerm:**
  - WezTerm 20240203-110809-5046fc22

- **Tmux:**
  - Tmux 3.2a

## System

- Docker Build: nvidia/cuda:11.8.0-devel-ubuntu22.04

## Additional Informations

```sh
In [15]: import matplotlib

In [16]: matplotlib.use('module://matplotlib-backend-wezterm')

In [17]: import matplotlib.pyplot as plt

In [18]: x = [1, 2, 3]

In [19]: y = [2, 3, 4]

In [20]: plt.plot(x, y)
Out[20]: [<matplotlib.lines.Line2D at 0x7f553c7b96f0>]

In [21]: plt.show()
14:40:47.133  ERROR  env_bootstrap > panic at wezterm/src/main.rs:383:10 - attempt to divide by zero
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_start_main
  16: <unknown>

thread 'main' panicked at wezterm/src/main.rs:383:10:
attempt to divide by zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

In [22]: x = [1, 2, 3]

In [23]: y = [2, 3, 4]

In [24]: plt.plot(x, y)
Out[24]: [<matplotlib.lines.Line2D at 0x7f553c63f460>]

In [25]: plt.show()
```

Sections from my neovim config:
```lua
	{
		"jpalardy/vim-slime",
		lazy = false,
		config = function()
			vim.g.slime_target = "tmux"
			vim.g.slime_default_config = { socket_name = "default", target_pane = "{last}" }
			vim.g.slime_dont_ask_default = 1
			vim.api.nvim_set_keymap("n", "<C-v><C-v>", "<Plug>SlimeLineSend", { noremap = false, silent = true })
			vim.api.nvim_set_keymap("n", "<C-c><C-c>", "<Plug>SlimeParagraphSend", { noremap = false, silent = true })
		end,
	},
-- 
map_keys(
	"n",
	"<leader>ip",
	[[<cmd>execute 'split | terminal tmux split-window -h ipython -i '.expand('%:p').' && tmux select-pane -L' | close<CR>]],
	{ noremap = true, silent = true }
)
```

**Comment by jpalardy** [comment]
hi @ucl98 

interesting! (especially wezterm being the one that complains)

let me do a few tests and get back to you

**Comment by jpalardy** [comment]
I don't run matplotlib myself, but I use nvim, tmux, and wezterm (on macos, but linux too if I needed to check) — and it doesn't seem to reproduce for me

some questions to try to corner this
- does it happen every time?
- does it happen if something else (another REPL) is running in the receiving pane?
- does it happen with another terminal emulator?

looking at the [wezterm code](https://github.com/wez/wezterm/blob/main/wezterm/src/main.rs#L382C1-L384C6) (from your error message)

![image](https://github.com/user-attachments/assets/4a499875-05b6-4269-9c17-dd932754dda8)

this seems to happen on a `width = 0` in the `ImgCatCommand` : `compute_image_cell_dimensions` function (which seems … weird?)

---

another line of inquiry:

you could try adding `echom` debug messages around [this code](https://github.com/jpalardy/vim-slime/blob/main/autoload/slime/targets/tmux.vim#L27-L29) and see what _EXACTLY_ gets passed in

---

let me know what you find ^

**Comment by ucl98** [comment]
Thanks for the fast response! I have a macbook (with m2 chip) and a laptop with intel i7 chip. I will test it on both devices and prepare a Dockercontainer that reproduces that issue.

**Comment by ucl98** [comment]
@jpalardy I have created a git-repo (https://github.com/ucl98/vim-slime_bug-report) with instructions and a Dockerfile. I just reproduced the error on my linux laptop with x86 architecture.

The same error happend when I was using kitty, and it might be linked to `matplotlib.use("module://matplotlib-backend-wezterm")`. I expected vim-slime to mirror my keyboard-input, but sending it to the tmux-panel behaved differently than typing it manually.

This issue is not of high priority, as I will look for alternatives (different terminals, packages, ...).

P.S.: I tested it outside of the Docker-Container and I had the same error

**Comment by jpalardy** [comment]
hi @ucl98 

I tried to download from your git-repo and I'm not sure about the whole thing :smile: 

What I mean:
- I open neovim, there are _some_ error messages (maybe nothing fatal), but it doesn't open python or anything else to slime to...
- there's a LOT of moving parts here, both in nvim (with all the plugins) and with python, matplotlib and that wezterm backend
- in the end, vim-slime calls the `tmux` executable and passes it arguments and content -- if you're trying to debug this, and find the problem there, we can have another go at it

my recommendation is to simplify your use case (by disabling plugins, etc) until you get to an [SSCCE](https://sscce.org/)

**Comment by ucl98** [comment]
thanks for the feedback. I updated the git-repo. It is minimal and still produces the error. I also added a .gif and an .mp4 to show the issue.
I'll take a closer look at the tmux executable. I'm new to both tmux and Neovim, so I don't have much experience debugging it yet. Once I make some progress, I'll provide an update here.

**Comment by ctorney** [comment]
this looks like an issue with tmux and wezterm imgcat - the matplotlib backend saves the plot as an image and then uses `wezterm imgcat` to display in the terminal. This isn't officially supported by tmux so it behaves weirdly.

Displaying an image within tmux works ok 
```
wezterm imgcat someimage.png
```
but sending the command to pane 1 from pane 0 doesn't work
```
echo "wezterm imgcat someimage.jpg" | tmux load-buffer -
tmux paste-buffer -d -t 1
``` 
This ends up showing the image in the active pane although the command is sent to the inactive pane - as shown here
<img width="1800" alt="Screenshot 2024-12-17 at 12 11 13" src="https://github.com/user-attachments/assets/7d676058-43d3-4fab-8ec1-7d66497dbd7a" />

This is what the tmux target is trying to do so would end up trying to display the image in the pane neovim is running in.

You can try to use the sixel backend - https://pypi.org/project/matplotlib-backend-sixel - I used to use this with tmux in wezterm but now I just use the wezterm multiplexer instead of tmux and that works well for me.

**Comment by ucl98** [comment]
Thats a great explanation for this confusing behavior. Thanks for the detailed explanation! I will try out sixel or wezterm-multiplexer :)
